//document.addEventListener('DOMContentLoaded '//fires when the initial html document has been loaded and parsed. But it doesn't wait for css and images    )
document.addEventListener('load',function(){

    const canvas = document.getElementById('canvas1');
const ctx = canvas.getContext('2d', {willReadFrequently: true});
canvas.width = 500;
canvas.height = 800;




class Game{
    constructor(){
        this.enemies = [];


    }
    update(){

    }

    draw(){

    }
    #addNewEnemy(){//a private method


    }
}

class Enemy{
    constructor(){

    }
    update(){

    }
    draw(){

    }

}

let lastTime=1;
function animate(timeStamp){//timeStamp arguement is automatically generated by requestAnimationFrame
    ctx.clearRect(0,0, canvas.width, canvas.height);
    //some code
    //difference in frames in animation is called deltatime
    const deltaTime =timeStamp-lastTime;
    lastTime= timeStamp;
    console.log(deltaTime)
    requestAnimationFrame(animate);
}
animate(0);


});